### ISSUE TITLE
Issue with Rotation on iPad

### ISSUE THREAD

**Issue by inPhilly** [maxep/MXSegmentedPager#9]
I am a novice programmer and I would fix this on a fork if I could. But it seems like constraints to its superview are not being set within the control.

I did get the control working in Storyboard. But when I use it in the detail view controller for a UISplitViewController, then rotate the view from portrait to landscape, the width of the control does not resize. I set the constraints from the MXSegmentedPager to its superview, but within the MXSegmentedPager itself, it doesn't seem like there are constraints set for the various components. 

Again, I would do it if I knew how. Just learning all of this.

Thanks again for this great control.

**Comment by maxep** [comment]
Hi,

Well its not very clear... I do not use constraints in the MXSegmentedPager, but I manually layout subviews. Which mean that you dont have do worry about subviews layout, you shouldn't add constraints   to the segmented-control, container or pages.
To see what is going wrong, you could add a breakpoint in the `layoutSubviews` method of the MXSegmentedPager and check when its getting called. If it doesn't get called when you rotate, it means that your constraints are not properly set to the MXSegmentedPager.
Also, on what ios version do you test ?

**Comment by inPhilly** [comment]
I have a UISplitView with a master controller and a Detail Controller. I am using MXSegmentedPager in the detail controller. I set up the Detail Controller in storyboard. I use a regular view controller and add a subview to the main view. It is the same size as the main view. I designate this subview as MXSegmentedPager. I hook it up via IB. I add constraints on all 4 sides to the superview. I start the app in Portrait orientation (both side of the UISplitview are always visible, in both orientations). It looks fine. I rotate the app to landscape. The MXSegmentedPager remains the same width as it was in portrait orientation (doesn't stretch all the way to the right), although it looks like the HMSegmentedControl has spaced out as if to accommodate the wider width. But it is only about 60% visible (left side, since the view has not stretched to the right). Sorry if I don't have the correct lingo. Does that make sense though?

**Comment by inPhilly** [comment]
Also, if there is content, that gets skewed on the rotation, and the header image view is the wrong size. I am sorry if I don't understand, but I thought you needed to add actual NSLayoutConstraints if using auto layout, either programmatically or via IB. I added the constraints between the control and my own view, but it does not seem to me that the control has NSLayoutConstraints for its own subviews? Since the control itself is not laid out in IB (subviews are added via code), I thought this had to be done programmatically? As I said, I am a novice, but this was my understanding.

**Comment by inPhilly** [comment]
I think auto layout is used by almost all controls these days, even when they are laid out manually? In the case when the control is laid out manually, the NSLayoutConstraints are just added programmatically, I believe. Because of the many different size/orientations of devices, I think that this is necessary. Again, the novice disclaimer, but this is what I have seen in many controls on this site and on CocoaControls.com, and from my own research. But please tell me if I am wrong!

**Comment by maxep** [comment]
Auto layout is a very good storyboard and nib tool to automatically add constraints. Constraints are only use to compute subviews's frame when it comes to `layoutSubviews`. In the MXSegmentedPager case, subviews frame are compute by `layoutWithHeight:` and `layoutContainer` when `reloadData` is called so It doesn't need to add any NSLayoutConstraint.
Adding constraints is not a necessary thing, it's just a way to layout your subviews.

Typically, you just have to add the MXSegmentedPager to your view, add your constraints and thats it. Thats working in my test.

Did you try with a breakpoint ?

**Comment by maxep** [comment]
Is that the issue you are facing when you rotate your ipad ?

![ios simulator screen shot 15 mai 2015 02 30 11](https://cloud.githubusercontent.com/assets/6815992/7644783/747647c4-faaa-11e4-8de2-06b6119822b0.png)

**Comment by inPhilly** [comment]
Mine doesn't look exactly the same but that is the general idea of what is happening when I use the example app in your repository. I think both could be solved by adding constraints? I didn't try setting a breakpoint because I don't know where I would set it or what I would be looking for (sorry).

**Comment by inPhilly** [comment]
I did figure out how to set the breakpoint as you said. Layout subviews is being called upon rotation. Still the problem persists.

**Comment by maxep** [comment]
Actually, I don't think this is your issue. I've just it using the ParallaxHeader category, and your description makes sense now! I thought you were using the standard class.
For the explanation, the parallax category add a scrolling subview which is not handled when `layoutSubviews` is called. Adding constraints may be the right choice. I will fix it asap...

**Comment by maxep** [comment]
First commit was a mistake, second one should fix the bug.

**Comment by inPhilly** [comment]
@maxep Thanks for all of your hard work on this. Your change did solve the issue with your example app, and it did go a long way towards solving my issues as well. Yet two issues remain:
1. On rotation from Portrait to landscape, the Header and the Segmented control now seem to rotate fine. But the content in the page seems to shift to a different page or an overlap between two pages on rotation.
2. For a view such as a webview, the frames are being set too wide. When I use the parallax controller as the detail controller of my splitview, the width of the webview seems to be always the entire width of the screen (in portrait), no matter which rotation.

It should be noted, probably for both issues, that for my split view, I always show both the detail and the master. So the detail view, which I am using this for, is never the entire width of the screen. The webview in MXSegmentedPager does not seem to realize this. I'm not sure the other views do either given issue 1? But I can't say for sure that both of the problems are related in this way. Though they both are definitely problems.

I tried adding constraints programmatically and failed. I only know how to do it in Storyboard. Sorry or I would fix this myself. Thanks again.

**Comment by maxep** [comment]
You are welcome.
Could you provide a sample code or send me project that reproduce these issues. English is not my native language and its a bit hard for me to understand the described behavior.

**Comment by inPhilly** [comment]
Okay. Issue #1 was because I didn't properly update all of my files from your changes. Sorry.

Issue #2 remains. I have altered your example app to show you but not sure how to get it to you. I added a UISplitViewController to the Storyboard and set it as the initial controller. I made MXSimpleViewController the Master and MSParallaxViewController the Detail. I added this code to viewDidLoad of MXSimpleViewController to make sure master would always show:

```
if ([self.splitViewController respondsToSelector:@selector(setPreferredDisplayMode:)]) {
    [self.splitViewController setPreferredDisplayMode:UISplitViewControllerDisplayModeAllVisible];
}
self.splitViewController.delegate = self;
```

Maybe you can do this yourself or tell me how to send you the sample project. 

If you run this you will see the issue above: 
"For a view such as a webview, the frames are being set too wide. When I use the parallax controller as the detail controller of my splitview, the width of the webview seems to be always the entire width of the screen (in portrait), no matter which rotation."

You will look at Webview in Portrait mode.

Hope this helps.

**Comment by inPhilly** [comment]
Just sent the two changed files (storyboard and MXSimpleViewController) to your email. Hope it helps.

**Comment by maxep** [comment]
OK I see now! This is not a issue, it depend on your UIWebView configuration and content. You should have a look on scalesPageToFit property .
But I'm more worried about the pages' contentOffset which wrongly goes to top when the parallax category rotates..

**Comment by inPhilly** [comment]
Oh yeah. Do you know how that can be fixed?

**Comment by inPhilly** [comment]
I am back working on this again and experiencing this problem right now. The contentOffset changes when the iPad rotates, which sets off this sequence

-[MXPagerView observeValueForKeyPath:ofObject:change:context:] 
-[MXPagerView didScrollFromPosition:ToPosition:] 
-[MXPagerView setIndex:] 
-[MXSegmentedPager pagerView:didMoveToPageAtIndex:] 

which calls:
[self.segmentedControl setSelectedSegmentIndex:index animated:NO];

So when I rotate the iPad, a different segment of the segmentedControl is selected.
